-- Script d'initialisation de la BDD du Tracker

CREATE TABLE HAND_HISTORY
(
  ID INTEGER NOT NULL auto_increment,
  CARD1 VARCHAR(2),
  CARD2 VARCHAR(2),
  VILLAIN1 VARCHAR(20),
  VILLAIN2 VARCHAR(20),
  VILLAIN3 VARCHAR(20),
  VILLAIN4 VARCHAR(20),
  VILLAIN5 VARCHAR(20),
  POT_PREFLOP INTEGER,
  POT_FLOP INTEGER,
  POT_TURN INTEGER,
  POT_RIVER INTEGER,
  WINNER VARCHAR(20),
  PRIMARY KEY(ID)
);

CREATE TABLE TEST_HAND
(
  CARD1 VARCHAR(2),
  CARD2 VARCHAR(2)
 );
 
 
