-- Script d'initialisation de la BDD du Tracker

CREATE TABLE HAND_HISTORY
(
  ID NUMBER NOT NULL auto_increment,
  CARD1 VARCHAR2(2),
  CARD2 VARCHAR2(2),
  VILLAIN1 VARCHAR2(20),
  VILLAIN2 VARCHAR2(20),
  VILLAIN3 VARCHAR2(20),
  VILLAIN4 VARCHAR2(20),
  VILLAIN5 VARCHAR2(20),
  POT_PREFLOP,
  POT_FLOP NUMBER,
  POT_TURN NUMBER,
  POT_RIVER NUMBER,
  WINNER VARCHAR2(20)
);
  
